services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && npx prisma db push && npm run start:dev"
