services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    
    ports:
      - '3000:3000'
    
    env_file:
      - .env.production
    
    environment:
      - NODE_ENV=production
    
    restart: unless-stopped
    
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      # - /usr/src/app/node_modules/.prisma